### ISSUE TITLE
Cannot find module '.../mol/build/-/node.test.js

### ISSUE THREAD

**Issue by timeshift92** [eigenmethod/mam#18]
Здравствуйте!
```
% npm run start

> @ start /Users/nurbek/Desktop/Projects/Learn/$mol/mam
> node ./mol/build/-/node.test.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/Users/nurbek/Desktop/Projects/Learn/$mol/mam/mol/build/-/node.test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node ./mol/build/-/node.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nurbek/.npm/_logs/2020-03-05T15_18_58_109Z-debug.log
```

сделал клон
потом npm install && npm run start

версия  нодый v12.7.0
npm 6.14.1
MacOs Catalina

**Comment by timeshift92** [comment]
кажется моя ошибка я начальную директорию назвал $mol  =)
