### ISSUE TITLE
Installing trouble

### ISSUE THREAD

**Issue by Yaroslav-Pryadunov** [eigenmethod/mam#6]
## Installing:
```
D:\dev\apps\mam>npm i

> undefined postinstall D:\dev\apps\mam
> echo Type 'npm start' to start dev server or 'npm start {relative/path}+' to build some packages.

Type 'npm start' to start dev server or 'npm start {relative/path}+' to build some packages.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 116 packages in 12.042s
```
## Starting:
```
D:\dev\apps\mam>npm start

> @ prestart D:\dev\apps\mam
> mam mol/build

D:/dev/apps/ecrm/client/$mol> git clone https://github.com/eigenmethod/mol.git mol
Error: Module not found: "mol/build"
    at $mol_build.modsRecursive (D:\dev\apps\mam\node_modules\build.node.ts:81:12)
    at $mol_atom.pull (D:\dev\apps\mam\atom\atom.ts:137:17)
    at $mol_atom.actualize (D:\dev\apps\mam\atom\atom.ts:126:23)
    at $mol_atom.get (D:\dev\apps\mam\atom\atom.ts:75:9)
    at $mol_atom.value (D:\dev\apps\mam\atom\atom.ts:298:17)
    at $mol_build.descr.value [as modsRecursive] (D:\dev\apps\mam\mem\mem.ts:73:17)
    at $mol_build.graph (D:\dev\apps\mam\node_modules\build.node.ts:381:9)
    at $mol_atom.pull (D:\dev\apps\mam\atom\atom.ts:137:17)
    at $mol_atom.actualize (D:\dev\apps\mam\atom\atom.ts:126:23)
    at $mol_atom.get (D:\dev\apps\mam\atom\atom.ts:75:9)

D:\dev\apps\mam\node_modules\build.node.ts:81
                                        throw new Error( `Module not found: "${mod.relate()}"` )
           ^
Error: Module not found: "mol/build"
    at $mol_build.modsRecursive (D:\dev\apps\mam\node_modules\build.node.ts:81:12)
    at $mol_atom.pull (D:\dev\apps\mam\atom\atom.ts:137:17)
    at $mol_atom.actualize (D:\dev\apps\mam\atom\atom.ts:126:23)
    at $mol_atom.get (D:\dev\apps\mam\atom\atom.ts:75:9)
    at $mol_atom.value (D:\dev\apps\mam\atom\atom.ts:298:17)
    at $mol_build.descr.value [as modsRecursive] (D:\dev\apps\mam\mem\mem.ts:73:17)
    at $mol_build.graph (D:\dev\apps\mam\node_modules\build.node.ts:381:9)
    at $mol_atom.pull (D:\dev\apps\mam\atom\atom.ts:137:17)
    at $mol_atom.actualize (D:\dev\apps\mam\atom\atom.ts:126:23)
    at $mol_atom.get (D:\dev\apps\mam\atom\atom.ts:75:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prestart: `mam mol/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yar\AppData\Roaming\npm-cache\_logs\2018-01-10T08_58_08_745Z-debug.log
```
## Starting after upgrading modules:
```
D:\dev\apps\mam>npm start

> @ prestart D:\dev\apps\mam
> mam mol/build

D:\dev\apps\mam\dom\context\context.node.ts:3
        $mol_dom_context = $node.jsdom.jsdom().defaultView as any
                                ^
TypeError: $node.jsdom.jsdom is not a function
    at $ (D:\dev\apps\mam\dom\context\context.node.ts:3:33)
    at Object.<anonymous> (D:\dev\apps\mam\dom\context\context.node.ts:5:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\dev\apps\mam\node_modules\mam\bin\mam:2:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prestart: `mam mol/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! $AppData\Roaming\npm-cache\_logs\2018-01-10T09_12_17_198Z-debug.log
```

**Comment by Yaroslav-Pryadunov** [comment]
Решено. Установка только через Git

**Comment by nin-jin** [comment]
Не очень понял. А вы как ставили?
